name: frontend-ci
on:
  push:
    paths:
      - '**.js'
  pull_request:
    paths:
      - '**.js'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: ls
