name: main-ci
on:
  push:
    paths:
      - '!docs/**'
  pull_request:
    paths:
      - '!docs/**'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: ls
