name: main-ci
on: ['push', 'pull_request']
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2

        - uses: dorny/paths-filter@v3
          id: filter
          with:
            filters: .github/file-filters.yml

        - name: Lint Frontend
          run: echo "Doing frontend"; pwd

        - name: Lint Backend
          if: ${{ steps.filter.outputs.backend == 'true' }}
          run: echo "Doing Backend";  pwd