name: main-ci
on: ['push', 'pull_request']
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2

        - uses: dorny/paths-filter@v2.2.1
          id: filter
          with:
            filters: |
                frontend:
                    - 'frontend/**'
                backend:
                    - '!frontend/**'
                    - '!docs/**'
                    - '!.github/workflows'

        - name: Lint Frontend
          if: ${{ steps.filter.outputs.frontend == 'true' || steps.filter.outputs.backend == 'true'}}
          run: echo "Doing frontend"; pwd

        - name: Lint Backend
          if: ${{ steps.filter.outputs.backend == 'true' }}
          run: echo "Doing Backend";  pwd